### ISSUE TITLE
‘httpuv’, ‘sourcetools’ had non-zero exit status

### ISSUE THREAD

**Issue by assetdaniyarov** [HajkD/LTRpred#1]
How can I solve this problem? when installing and starting a pepline

> biocLite("HajkD/LTRpred")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.4 (2018-03-15).
Installing github package(s) ‘HajkD/LTRpred’
Downloading GitHub repo HajkD/LTRpred@master
from URL https://api.github.com/repos/HajkD/LTRpred/zipball/master
Installing LTRpred
пробую URL 'https://cloud.r-project.org/src/contrib/amap_0.8-14.tar.gz'
Content type 'application/x-gzip' length 259358 bytes (253 KB)
==================================================
downloaded 253 KB

Installing amap
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL '/tmp/Rtmp2VZBrC/devtools61bed5b1463/amap'  \
  --library='/home/aset/R/x86_64-pc-linux-gnu-library/3.4' --install-tests 

* installing *source* package ‘amap’ ...
** пакет ‘amap’ удачно распакован, MD5 sums проверены
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for pthread_create in -lpthread... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++  -I/usr/share/R/include -DNDEBUG -I/usr/local/include/       -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c acprob.cpp -o acprob.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I/usr/local/include/       -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c burt.c -o burt.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I/usr/local/include/       -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c diss.c -o diss.o
g++  -I/usr/share/R/include -DNDEBUG -I/usr/local/include/       -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c distance.cpp -o distance.o
g++  -I/usr/share/R/include -DNDEBUG -I/usr/local/include/       -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hclust.cpp -o hclust.o
g++  -I/usr/share/R/include -DNDEBUG -I/usr/local/include/       -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c kmeans.cpp -o kmeans.o
g++  -I/usr/share/R/include -DNDEBUG -I/usr/local/include/       -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c matrice.cpp -o matrice.o
gfortran   -fpic  -g -O2 -fstack-protector-strong  -c pop.f -o pop.o
/bin/bash: gfortran: команда не найдена
/usr/lib/R/etc/Makeconf:182: recipe for target 'pop.o' failed
make: *** [pop.o] Error 127
ERROR: compilation failed for package ‘amap’
* removing ‘/home/aset/R/x86_64-pc-linux-gnu-library/3.4/amap’
Installation failed: Command failed (1)
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL '/tmp/Rtmp2VZBrC/devtools61be2461ee30/HajkD-LTRpred-fe9851d'  \
  --library='/home/aset/R/x86_64-pc-linux-gnu-library/3.4' --install-tests 

ERROR: dependency ‘amap’ is not available for package ‘LTRpred’
* removing ‘/home/aset/R/x86_64-pc-linux-gnu-library/3.4/LTRpred’
Installation failed: Command failed (1)
installation path not writeable, unable to update packages: XML, cluster,
  foreign, MASS, Matrix, nlme, survival
>

**Comment by HajkD** [comment]
Hi @aset8,

It seems like you need to install the package `amap` before being able to install LTRpred.
Did you already install all tools and dependencies as specified here in the Introduction https://hajkd.github.io/LTRpred/articles/Introduction.html#installation ?

Many thanks and best wishes,
Hajk
