### ISSUE TITLE
R installation instructions need to be updated

### ISSUE THREAD

**Issue by mdozmorov** [HajkD/LTRpred#12]
When tested on a clean R/Rstudio installation (rocker/rstudio), the installation instructions require manual intervention

````
install.packages(c("tidyverse", "data.table", "seqinr", "biomartr", "ape", "dtplyr", "devtools"))

ERROR: dependencies ‘biomaRt’, ‘Biostrings’ are not available for package ‘biomartr’
* removing ‘/usr/local/lib/R/site-library/biomartr’
Warning in install.packages :
  installation of package ‘biomartr’ had non-zero exit status
````

Installing `biomaRt` and `Biostrings` and then installing `biomartr` worked. Please, adjust accordingly.

**Comment by HajkD** [comment]
Dear Mikhail,

Thank you very much for making me aware of this issue.

I just changed the orders of the installation instructions and pushed the new version to GitHub.

Many thanks,
Hajk
