### ISSUE TITLE
Running LTRpred docker container in userspace with udocker

### ISSUE THREAD

**Issue by ibebio** [HajkD/LTRpred#16]
The LTRpred docker container can be run on systems where docker is not available and root privileges are not an option via [udocker](https://github.com/indigo-dc/udocker).  Udocker is written in Python and can be installed via pip. The following sequence of commands starts up the LTRpred container in user space:
```
# Create and activate conda environment, optional
conda create -n udocker_prod -c defaults python=2.7
conda activate udocker_prod

# Install most recent version from udocker github repo
pip install git+https://github.com/indigo-dc/udocker

# Prepare container
udocker pull drostlab/ltrpred
udocker create --name=ltrpred drostlab/ltrpred

# Required on some systems to run the container
export PROOT_NO_SECCOMP=1

# Run container
udocker run ltrpred
```

**Comment by HajkD** [comment]
Dear Ilja,

Thank you so much for this absolutely brilliant suggestion! 

This will help a lot of users to run the `LTRpred` Docker container in a `Conda` environment and doesn't require a conversion to [Singularity containers](https://singularity.lbl.gov/).

Many thanks,
Hajk

**Comment by 123jjhy** [comment]
Hi,
I downloaded in the way mentioned above and got an error：
 fatal: unable to access 'https://github.com/indigo-dc/udocker/': Empty reply from server
ERROR: Command errored out with exit status 128: git clone -q https://github.com/indigo-dc/udocker /tmp/pip-req-build-GdR84J Check the logs for full command output.

**Comment by 123jjhy** [comment]
Hi,
Ask if this method also necessarily requires root permissions?
![Uploading image.png…]()

**Comment by HajkD** [comment]
Not when it is converted to a Singularity Container.

**Comment by 123jjhy** [comment]
What is a Singularity Container？ I am a green hands，could you give me some more Pointers？

**Comment by HajkD** [comment]
https://docs.sylabs.io/guides/3.5/user-guide/introduction.html

**Comment by 123jjhy** [comment]
OK. Thank you.
