### ISSUE TITLE
Small details on the vignette

### ISSUE THREAD

**Issue by dcassol** [HajkD/LTRpred#17]
Dear @HajkD, 
Congratulations on the software! I only have three minor points to comment:

1. 
https://github.com/HajkD/LTRpred/blob/26bda714253be86c26ac3b178a5da14003b6c4e0/vignettes/Introduction.Rmd#L154
Update to:` docker run --rm -p 8787:8787 -v /put/here/your/path/to/ltrpred_data:/app/ltrpred_data -ti drostlab/ltrpred`

2. 
https://github.com/HajkD/LTRpred/blob/26bda714253be86c26ac3b178a5da14003b6c4e0/vignettes/Introduction.Rmd#L183
```
[1] "Successful job 1 ."
Warning message:
`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
```
Just a suggestion to update to `tibble()`.

3. 
https://github.com/HajkD/LTRpred/blob/26bda714253be86c26ac3b178a5da14003b6c4e0/vignettes/Introduction.Rmd#L262
You want to add the link to the section here. 

Also, I think you could provide a few details/instructions on how to copy the results from the container to the host.

**Comment by HajkD** [comment]
Dear Dani,

thank you so much for these brilliant suggestions!
 
- Point 1.) I fixed the path name: https://github.com/HajkD/LTRpred/commit/bfee290e61b9041839ff67f2d891bb69c46f34ef .
- Point 2.) I fixed the depreciated `tibble::data_frame()` call here: https://github.com/HajkD/LTRpred/commit/f9054205c3cd8ff7367958970af82ac8f920fe51
The changes will go live with the new container version of `LTRpred`.
- Point 3.) As suggested, I added the link here: https://github.com/HajkD/LTRpred/commit/fe54f08a81f52a4e41e54107874c96e2fc647f0d
- Point 4.) I added a section to guide users for who wish to retrieve the `LTRpred` results from their container back to their local machine: https://github.com/HajkD/LTRpred/commit/c95637ecb23fd56d4f1330b8c04201fcdf7beea6. 

I hope that everything is according to what you had in mind? 

Your help with improving `LTRpred` is truly appreciated!

Many thanks,
Hajk
