### ISSUE TITLE
Paper typo

### ISSUE THREAD

**Issue by dcassol** [HajkD/LTRpred#18]
Dear @HajkD,

I believe there is a typo here:
https://github.com/HajkD/LTRpred/blob/master/paper.md `line 33`
> Here, we introduce the ``LTRpred`` pipeline which allows to _de novo_ annotate functional and **_thuse_** potentially...

**Comment by HajkD** [comment]
Dear Dani,

Thank you very much for spotting the typo!

It is fixed now.
