### ISSUE TITLE
How can I solve this problem?

### ISSUE THREAD

**Issue by assetdaniyarov** [HajkD/LTRpred#2]
> library(LTRpred)
> LTRpred(genome.file = system.file("/home/aset/lic.fa", package = "LTRpred"), cluster = TRUE, cores = 4)
vsearch v2.8.0_linux_x86_64, 7.7GB RAM, 8 cores
https://github.com/torognes/vsearch

No hmm files were specified, thus the internal HMM library will be used! See '/usr/local/lib/R/site-library/LTRpred/HMMs/hmm_*' for details.
No tRNA files were specified, thus the internal tRNA library will be used! See '/usr/local/lib/R/site-library/LTRpred/tRNAs/tRNA_library.fa' for details.
Folder '_ltrpred' does not exist yet and will be created...
Folder '_ltrpred' exists already and will be used...
Starting LTRpred analysis...
Step 1:
Run LTRharvest...
LTRharvest: Generating index file _ltrharvest/_index.fsa with gt suffixerator...
gt suffixerator: error: missing argument to option "-db"
Running LTRharvest and writing results to _ltrharvest...
LTRharvest analysis finished!
Step 2:
Generating index file _ltrdigest/_index_ltrdigest.fsa with suffixerator...
gt suffixerator: error: missing argument to option "-db"
LTRdigest: Sort index file...
fopen(): cannot open file '_ltrharvest/_Prediction.gff': No such file or directory
Running LTRdigest and writing results to _ltrdigest...
gt ltrdigest: error: fopen(): cannot open file '_ltrdigest/_index_ltrdigest.fsa.esq': No such file or directory
LTRdigest analysis finished!
Step 3:
Import LTRdigest Predictions...
Ошибка: The file '_ltrdigest/-ltrdigest_tabout.csv' does not exist! Please check the correct path or the correct output of LTRharvest() or LTRdigest().
> 

Please, send me detailed instructions for installing and configuring LTRpred

I know how to install dependencies (like, RepeatMasker, HMMER, LTR_harvest and other), but I do not know how to properly configure the paths and freely run the program.

Thanks!

**Comment by HajkD** [comment]
Hi @aset8,

```
library(LTRpred)
LTRpred(genome.file = "/home/aset/lic.fa", cluster = TRUE, cores = 4)
```
should work.

 The command ```system.file(... , package = "LTRpred")``` refers only to my example file which is part of the CRAN policy to storing example files in R packages.

The problem of your command run was that LTRpred couldn't find the input files.

I hope this helps.

Best wishes,
Hajk
