### ISSUE TITLE
Running LTRPred

### ISSUE THREAD

**Issue by Ramkyeri** [HajkD/LTRpred#26]
Dear HajKD,

it shows the following errors

43386814-085a-3de5-9412-e014919ca2fa
Error: invalid container name may already exist or wrong format

![image](https://user-images.githubusercontent.com/70749594/161718020-5723f296-9549-40a8-a2c6-a0d3bf247484.png)

![image](https://user-images.githubusercontent.com/70749594/161729092-f5ef4a54-80bb-44ea-991a-b295864787e7.png)

with regards

Ramky

**Comment by ericadinatale** [comment]
Hi Ramky, 

I had the same issue and I did the following:
- Remove the previous udocker_prod environment
- conda create -n udocker_prod -c defaults python=3.6 'setuptools<58'
- conda activate udocker_prod
- pip install ...

The above worked for me.

Hope this helps!
Erica

**Comment by Ramkyeri** [comment]
Dear Erica, 

thank you so much for your suggestion,  I will try this. 

with regards 

Ramky

**Comment by HajkD** [comment]
I assume this worked now.

Many thanks, Erica!
