### ISSUE TITLE
LTRpred installation in R failed: "Installation failed: Empty reply from server"

### ISSUE THREAD

**Issue by CristianRiccio** [HajkD/LTRpred#3]
I have tried to install LTRpred in R but I failed:

```
biocLite("HajkD/LTRpred")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.4 (2018-03-15).
Installing github package(s) ‘HajkD/LTRpred’
Downloading GitHub repo HajkD/LTRpred@master
from URL https://api.github.com/repos/HajkD/LTRpred/zipball/master
Installation failed: Empty reply from server
```

I work on MacOS X.

Does this mean that the server hosting LTRpred is off?

**Comment by CristianRiccio** [comment]
I tried again later and it worked. Maybe my internet connection was too slow?

**Comment by HajkD** [comment]
Hi @CristianRiccio 

Thank you for contacting me.

Yes, I assume your internet connection was not stable enough to download the package from the GitHub page.

I am happy that you managed now.

Cheers,
Hajk
