### ISSUE TITLE
could not install biocLite.R

### ISSUE THREAD

**Issue by wangj2009** [HajkD/LTRpred#8]
**> source("http://bioconductor.org/biocLite.R")**
 Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install 

**> BiocManager::install(c("biocLite.R"))**
Bioconductor version 3.9 (BiocManager 1.30.7), R 3.6.1 (2019-07-05)
Installing package(s) 'biocLite.R'
Warning message:
package ‘biocLite.R’ is not available (for R version 3.6.1)

**Comment by wangj2009** [comment]
I could not find LTRpred or HajkD in Bioconductor.
https://www.bioconductor.org/packages/release/BiocViews.html#___Software

**Comment by HajkD** [comment]
Hi,

`LTRpred` itself is not on Bioconductor, but `LTRpred` uses some Bioconductor packages as dependencies. So it is more convenient to use their `BiocManager::install()` function to install everything.

You can also try the following:

```r
library(devtools)
install_github("HajkD/LTRpred", build_vignettes = TRUE, dependencies = TRUE)
```
